### ISSUE TITLE
Build Error: custom_rasterizer fails to compile on Windows with PyTorch 2.9.1+cu130 (error C2872: "std": ambiguous symbol)

### ISSUE THREAD

**Issue by flying-swine** [kijai/ComfyUI-Hunyuan3DWrapper#204]
When the system attempts to JIT-compile the `custom_rasterizer` extension on a Windows machine using the bleeding-edge PyTorch 2.9.1+cu130 and CUDA 13.0, the build fails. 

The MSVC compiler (`cl.exe`) combined with `nvcc` throws an ambiguous symbol error (`error C2872: 'std': ambiguous symbol`) inside PyTorch's `compiled_autograd.h`. This appears to be a namespace collision issue triggered by C++ standard library changes in CUDA 13.0 / MSVC when parsing PyTorch headers.

### Environment
* **OS:** Windows 10 / 11
* **GPU:** RTX 4060 8GB
* **Python:** 3.10 (via ComfyUI-aki-v3 portable package)
* **PyTorch version:** 2.9.1+cu130
* **CUDA Toolkit:** 13.0
* **Compiler:** MSVC (`cl.exe`) + `nvcc`

### Error Traceback
```text
tmpxft_00002884_00000000-7_rasterizer_gpu.cudafe1.cpp
H:/ComfyUI-aki/ComfyUI-aki-v3/ComfyUI-aki-v3/python/Lib/site-packages/torch/include\torch/csrc/dynamo/compiled_autograd.h(1134): error C2872: 'std': ambiguous symbol
H:/ComfyUI-aki/ComfyUI-aki-v3/ComfyUI-aki-v3/python/Lib/site-packages/torch/include\c10/cuda/CUDAStream.h(261): note: could be 'std'
H:/ComfyUI-aki/ComfyUI-aki-v3/ComfyUI-aki-v3/python/Lib/site-packages/torch/include\torch/csrc/dynamo/compiled_autograd.h(1134): note: or 'std'
H:/ComfyUI-aki/ComfyUI-aki-v3/ComfyUI-aki-v3/python/Lib/site-packages/torch/include\torch/csrc/dynamo/compiled_autograd.h(1108): note: while compiling class template member function 'c10::TypePtr torch::dynamo::autograd::IValuePacker<__int64>::packed_type(void)'
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.0\\bin\\nvcc.EXE' failed with exit code 2
```
### Workaround / Temporary Fix
Since there is no pre-built .whl available for cp310 + cu130 yet, users have to compile it locally. The compilation can be successfully completed by applying a minor patch to the PyTorch header file to bypass the namespace collision.

Open [venv_path]/Lib/site-packages/torch/include/torch/csrc/dynamo/compiled_autograd.h

Navigate to line 1134.

Comment out the specific if constexpr block handling ::std::string:
```
// } else if constexpr (::std::is_same_v<T, ::std::string>) {
//     return at::StringType::get();
// }
```

After commenting out these lines, restarting ComfyUI allows the JIT compilation to finish successfully without affecting the functionality of the 3D generation workflow.

Posting this here to help anyone else who might be running the latest PyTorch/CUDA environments on Windows and getting stuck at the compiling stage. It might also be helpful to provide a pre-built wheel for cu130 in future releases!
